"""Models layer (Data Access) - Database models and CRUD operations."""

from .database import (
    Database,
    ConnectionPool,
    Transaction,
    DatabaseError,
    ConnectionError,
    TransactionError,
    PoolExhaustedError,
    ConnectionConfig,
    QueryResult,
)

# Project model exports
from .project import (
    Project,
    ProjectCreate,
    ProjectUpdate,
    ProjectStatus,
    ProjectError,
    ProjectNotFoundError,
    ProjectInvalidStatusError,
    ProjectAlreadyDeletedError,
    ProjectManager,
)

# Character model exports
from .character import (
    Character,
    CharacterCreate,
    CharacterUpdate,
    CharacterWithStats,
    VoiceProfile,
    CharacterError,
    CharacterNotFoundError,
    CharacterAlreadyDeletedError,
    InvalidFirstFrameError,
    ProjectMismatchError,
    CharacterManager,
)

# Task model exports
from .task import (
    Task,
    TaskCreate,
    TaskUpdate,
    TaskWithStats,
    TaskStatus,
    TaskType,
    TaskError,
    TaskNotFoundError,
    TaskAlreadyExistsError,
    InvalidTaskStatusError,
    InvalidPriorityError,
    ProgressError,
    TaskManager,
)

# Script Line model exports
from .script_lines import (
    ScriptLine,
    ScriptLineCreate,
    ScriptLineUpdate,
    ScriptLineWithStats,
    ScriptLineError,
    ScriptLineNotFoundError,
    ScriptLineAlreadyExistsError,
    InvalidSequenceError,
    CharacterMismatchError,
    ScriptLineManager,
)

# Shot model exports
from .shot import (
    Shot,
    ShotCreate,
    ShotUpdate,
    ShotWithStats,
    ShotStatus,
    ShotError,
    ShotNotFoundError,
    ShotAlreadyExistsError,
    InvalidShotStatusError,
    ShotGenerationError,
    SimilarityScoreError,
    ResourceNotFoundError,
    ShotManager,
)

# System Config model exports
from .system_config import (
    SystemConfig,
    SystemConfigCreate,
    SystemConfigUpdate,
    TypedConfig,
    ConfigType,
    SystemConfigError,
    ConfigNotFoundError,
    ConfigAlreadyExistsError,
    ConfigValidationError,
    ConfigValueError,
    SystemConfigManager,
)

# API Quotas model exports
from .api_quotas import (
    ApiQuota,
    ApiQuotaCreate,
    ApiQuotaUpdate,
    QuotaUsage,
    QuotaReservation,
    ServiceName,
    ApiQuotaError,
    QuotaNotFoundError,
    QuotaExhaustedError,
    InvalidQuotaAmountError,
    ServiceDisabledError,
    QuotaResetError,
    ReservationNotFoundError,
    ApiQuotaManager,
)

__all__ = [
    # Database infrastructure
    "Database",
    "ConnectionPool",
    "Transaction",
    "DatabaseError",
    "ConnectionError",
    "TransactionError",
    "PoolExhaustedError",
    "ConnectionConfig",
    "QueryResult",
    # Project model
    "Project",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectStatus",
    "ProjectError",
    "ProjectNotFoundError",
    "ProjectInvalidStatusError",
    "ProjectAlreadyDeletedError",
    "ProjectManager",
    # Character model
    "Character",
    "CharacterCreate",
    "CharacterUpdate",
    "CharacterWithStats",
    "VoiceProfile",
    "CharacterError",
    "CharacterNotFoundError",
    "CharacterAlreadyDeletedError",
    "InvalidFirstFrameError",
    "ProjectMismatchError",
    "CharacterManager",
    # Task model
    "Task",
    "TaskCreate",
    "TaskUpdate",
    "TaskWithStats",
    "TaskStatus",
    "TaskType",
    "TaskError",
    "TaskNotFoundError",
    "TaskAlreadyExistsError",
    "InvalidTaskStatusError",
    "InvalidPriorityError",
    "ProgressError",
    "TaskManager",
    # Script Line model
    "ScriptLine",
    "ScriptLineCreate",
    "ScriptLineUpdate",
    "ScriptLineWithStats",
    "ScriptLineError",
    "ScriptLineNotFoundError",
    "ScriptLineAlreadyExistsError",
    "InvalidSequenceError",
    "CharacterMismatchError",
    "ScriptLineManager",
    # Shot model
    "Shot",
    "ShotCreate",
    "ShotUpdate",
    "ShotWithStats",
    "ShotStatus",
    "ShotError",
    "ShotNotFoundError",
    "ShotAlreadyExistsError",
    "InvalidShotStatusError",
    "ShotGenerationError",
    "SimilarityScoreError",
    "ResourceNotFoundError",
    "ShotManager",
    # System Config model
    "SystemConfig",
    "SystemConfigCreate",
    "SystemConfigUpdate",
    "TypedConfig",
    "ConfigType",
    "SystemConfigError",
    "ConfigNotFoundError",
    "ConfigAlreadyExistsError",
    "ConfigValidationError",
    "ConfigValueError",
    "SystemConfigManager",
    # API Quotas model
    "ApiQuota",
    "ApiQuotaCreate",
    "ApiQuotaUpdate",
    "QuotaUsage",
    "QuotaReservation",
    "ServiceName",
    "ApiQuotaError",
    "QuotaNotFoundError",
    "QuotaExhaustedError",
    "InvalidQuotaAmountError",
    "ServiceDisabledError",
    "QuotaResetError",
    "ReservationNotFoundError",
    "ApiQuotaManager",
]